---
title: "Modeling NIH funding data"
author: "Jay Hesselberth"
date: "March 11, 2015"
output: html_document
---

```{r load.libs, warning = FALSE, message = FALSE}
require(dplyr)
require(nihexporter)
```

Model the number of publications as a function of duration, dollars and activity code.

```{r pub.model.1}
activity.spec <- c('R01','P01')

projects_data <- projects %>%
  # get a subset of the data
  sample_frac(0.05) %>%
  select(project.num, activity, project.start, project.end, total.cost) %>%
  group_by(project.num, activity) %>%
  summarize(duration = max(project.end) - min(project.start),
            dollars = sum(total.cost)) %>%
  filter(!is.na(duration) & dollars > 0)

projects_data

pub_data <- projects_data %>%
  inner_join(publinks) %>%
  group_by(project.num) %>%
  summarize(n.pubs = n()) %>%
  select(project.num, n.pubs)

pub_data

patent_data <- projects_data %>%
  inner_join(patents) %>%
  group_by(project.num) %>%
  summarize(n.patents = n()) %>%
  select(project.num, n.patents)

patent_data

model_tbl <- projects_data %>%
  left_join(pub_data) %>%
  left_join(patent_data) %>%
  select(activity, duration, dollars, n.pubs, n.patents) 

model_tbl

lmfit <- sjp.lm(n.pubs ~ duration + dollars + activity,  data = model_tbl)

par(mfrow = c(2,2))
plot(lmfit)
```